name: Sync with Upstream Repository

on:
  schedule:
    - cron: '0 15 * * *'  # Runs every day at 3 PM UTC
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/CentreForDigitalHumanities/INFOMPPM.git || echo "Upstream already exists"
          git fetch upstream

      - name: Ensure Main Branch Exists
        run: |
          git fetch origin main
          git checkout main

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge --allow-unrelated-histories -s ours upstream/main

     
      - name: Push Changes to Fork
        env:
          MY_PAT: ${{ secrets.infoppm }}
        run: |
          git push https://x-access-token:${MY_PAT}@github.com/hku1/INFOMPPM.git main || echo "No changes to push"
